# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20160323_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='book.Books')),
            ],
            options={
                'verbose_name_plural': 'Book Page Metadata',
            },
        ),
    ]
