# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_seometadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='seometadata',
            name='seo_done',
            field=models.BooleanField(default=False),
        ),
    ]
