# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20160324_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
